# Generated by Django 5.0.7 on 2024-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=700)),
                ("chooseus", models.CharField(max_length=400)),
                ("visionary", models.CharField(max_length=400)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog")),
            ],
        ),
    ]
