# Generated by Django 5.0.7 on 2024-07-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abouts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chooseus", models.CharField(max_length=400)),
                ("visionary", models.CharField(max_length=400)),
                (
                    "chooseus_img",
                    models.ImageField(blank=True, null=True, upload_to="blog"),
                ),
                (
                    "visionary_img",
                    models.ImageField(blank=True, null=True, upload_to="blog"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="about",
            name="chooseus",
        ),
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
        migrations.RemoveField(
            model_name="about",
            name="visionary",
        ),
    ]
