# Generated by Django 5.0.7 on 2024-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blogs", "0003_delete_about_delete_abouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aboutus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=800)),
                ("chooseus", models.CharField(max_length=800)),
                ("visionary", models.CharField(max_length=800)),
                (
                    "chooseus_img",
                    models.ImageField(blank=True, null=True, upload_to="blog"),
                ),
                (
                    "visionary_img",
                    models.ImageField(blank=True, null=True, upload_to="blog"),
                ),
            ],
        ),
    ]
