# Generated by Django 5.0.7 on 2024-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=800)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="chooseus_img",
            field=models.ImageField(upload_to="about_images/"),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="visionary_img",
            field=models.ImageField(upload_to="vison/"),
        ),
    ]
